# Generated by Django 4.2 on 2023-05-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_name',
            field=models.TextField(blank=True, max_length=15, null=True),
        ),
    ]
